# Modified version of https://github.com/sosedoff/pgweb/blob/master/docker-compose.yml
services:
  # docker compose up postgres -d
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5433:5432
    # Disabling persistence to allow for the program to be run multiple times
    volumes:
      - data:/var/lib/postgresql/data
    # environment:
    #   POSTGRES_DB: "db"
    #   POSTGRES_PASSWORD: "dbpass"
    #   POSTGRES_USER: "dbuser"
    env_file:
      - .env
    healthcheck:
      # https://stackoverflow.com/a/73049146
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
    networks:
      - db-net
  rathercurious-mastodon:
    container_name: rathercurious-mastodon
    # Build ./Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - db-net
    depends_on:
      postgres:
        condition: service_healthy
  # pgweb is a web-based database browser for PostgreSQL if you want to check the database via a web interface
  # pgweb:
  #   container_name: pgweb
  #   image: sosedoff/pgweb
  #   ports:
  #     - 8081:8081
  #   env_file:
  #     - .env
  #   networks:
  #     - db-net
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
  #     interval: 5s

volumes:
  data:
    name: rathercurious-mastodon

networks:
  db-net:
    name: db-net